from .near_zeros import generate_near_zeros
from .sparse import get_sparse_target
from .block import create_block_diagonal_matrix
from .toeplitz import precise_toeplitz_multiple_channels, approximate_toeplitz_multiple_channels
from .average2d import create_average_kernel
from .conv2d import create_conv2d_weight_mask, create_conv2d_bias_transformation
from .padding import create_padding_transformation_matrix, create_inverse_padding_transformation_matrix
